version: "3.3"

services:
  mongo_db:
    container_name: db_container
    image: mongo:latest
    restart: unless-stopped
    volumes:
      - mongo_db:/data/db
  api:
    build: .
    ports:
      - 5000:3000
    environment:
      PORT: 3000
      DB_PORT: 27017
      DB_HOST: mongo_db
      DB_DATABASE: songs-db
    depends_on:
      - mongo_db

volumes:
  mongo_db: {}
